import fg from 'fast-glob';
import fs from 'node:fs/promises';
import path from 'node:path';
import YAML from 'yaml';
import { DocgenError, describeUnknownError } from '../util/errors.js';
import { toPosix } from '../util/paths.js';
import { compareStrings } from '../util/sort.js';
import { CARDS_DIR } from '../config/paths.js';
import { featureCardSchema } from './types.js';
import type { FeatureCard } from './types.js';

/**
 * Persistence for generated feature cards.
 *
 * Cards are stored as data rather than only as rendered markdown, because the
 * next run needs to compare their input hash to decide whether to pay for
 * regeneration. Keeping them in the repo means CI reuses a developer's work
 * instead of re-running every surface on every build.
 */
export { CARDS_DIR } from '../config/paths.js';

export async function loadCards(root: string): Promise<ReadonlyMap<string, FeatureCard>> {
  const files = (await fg([`${CARDS_DIR}/*.yaml`], { cwd: root, onlyFiles: true }))
    .map(toPosix)
    .sort(compareStrings);

  const cards = new Map<string, FeatureCard>();

  for (const relative of files) {
    let parsed: unknown;
    try {
      parsed = YAML.parse(await fs.readFile(path.join(root, relative), 'utf8'));
    } catch (cause) {
      throw new DocgenError({
        code: 'card-unparseable',
        message: `${relative} is not valid YAML: ${describeUnknownError(cause)}`,
        remedy: `Delete the file to regenerate it, or fix the syntax. Cards live in ${CARDS_DIR}/.`,
        file: relative,
        cause,
      });
    }

    if (parsed === null || typeof parsed !== 'object') continue;
    const record = parsed as Record<string, unknown>;

    const body = featureCardSchema.safeParse(record['body']);
    // A card whose stored body no longer validates is treated as absent, so it
    // regenerates. Rendering a half-valid card would publish claims that never
    // passed the evidence check.
    if (!body.success) continue;

    const surfaceId = record['surfaceId'];
    const slug = record['slug'];
    if (typeof surfaceId !== 'string' || typeof slug !== 'string') continue;

    cards.set(surfaceId, {
      surfaceId,
      slug,
      title: typeof record['title'] === 'string' ? record['title'] : slug,
      kind: typeof record['kind'] === 'string' ? record['kind'] : 'screen',
      body: body.data,
      producedBy: typeof record['producedBy'] === 'string' ? record['producedBy'] : 'unknown',
      inputHash: typeof record['inputHash'] === 'string' ? record['inputHash'] : '',
      promptVersion: typeof record['promptVersion'] === 'string' ? record['promptVersion'] : '',
      answered: Array.isArray(record['answered'])
        ? record['answered'].filter((value): value is string => typeof value === 'string')
        : [],
    });
  }

  return cards;
}

export async function saveCards(root: string, cards: readonly FeatureCard[]): Promise<readonly string[]> {
  const written: string[] = [];

  for (const card of cards) {
    const relative = `${CARDS_DIR}/${card.slug}.yaml`;
    const absolute = path.join(root, relative);
    await fs.mkdir(path.dirname(absolute), { recursive: true });
    await fs.writeFile(absolute, renderCardFile(card), 'utf8');
    written.push(relative);
  }

  return written.sort(compareStrings);
}

export function renderCardFile(card: FeatureCard): string {
  const header = [
    '# Generated by docgen. This is model-inferred content, not verified fact.',
    '# Every claim here is badged in the rendered documentation. Do not hand-edit:',
    "# to correct something, answer the relevant question with `docgen answer`,",
    '# which records your answer as ground truth instead.',
    '',
  ].join('\n');

  return `${header}${YAML.stringify(
    {
      surfaceId: card.surfaceId,
      slug: card.slug,
      title: card.title,
      kind: card.kind,
      producedBy: card.producedBy,
      promptVersion: card.promptVersion,
      inputHash: card.inputHash,
      answered: [...card.answered].sort(compareStrings),
      body: card.body,
    },
    { lineWidth: 100 },
  )}`;
}
