import type { ExtractorId } from '../../types/core.js';
import type { RunResult } from '../../pipeline.js';
import { EXTRACTOR_IDS } from '../../types/core.js';
import { cell, renderFrontMatter, section, sourceLink, table, warning } from '../markdown.js';
import type { FindingsReport } from '../../analysis/findings.js';
import { sortItems } from '../../analysis/findings.js';

/** Page filenames, so the index and the writer cannot disagree. */
export const PAGE_FILES: Readonly<Record<ExtractorId, string | undefined>> = Object.freeze({
  routes: 'routes.md',
  endpoints: 'api.md',
  schema: 'schema.md',
  jobs: 'jobs.md',
  config: 'config.md',
  // The module graph is a diagram; a table of 400 modules helps nobody.
  deps: undefined,
});

const PAGE_TITLES: Readonly<Record<ExtractorId, string>> = Object.freeze({
  routes: 'Routes and screens',
  endpoints: 'API endpoints',
  schema: 'Database schema',
  jobs: 'Background jobs',
  config: 'Environment and configuration',
  deps: 'Module dependency graph',
});

/**
 * README.md — the index, and the only page carrying a timestamp (SPEC 6.2).
 *
 * It also carries the coverage summary, because this is where a reader arrives
 * first and therefore where the limits of the documentation have to be stated.
 */
export function renderReadme(run: RunResult, findings?: FindingsReport): string {
  const head = renderFrontMatter({
    title: 'Generated documentation',
    confidence: 'verified',
    context: run.context,
    includeTimestamp: true,
  });

  let body = `${head}# Generated documentation\n\n`;
  body += 'Everything here is derived from the code by static analysis. No part of it was written ';
  body += 'by a person or generated by a language model, and every entry links to the source it ';
  body += 'came from so any statement can be checked in one click.\n\n';

  if (run.stack.unsupported.length > 0) {
    body += warning([
      'This documentation is **incomplete**. docgen detected technology it cannot read:',
      '',
      ...run.stack.unsupported.map(
        (tech) =>
          `- **${tech.name}** (\`${tech.evidence.file}\`)` +
          (tech.unsupportedNote === undefined ? '' : ` — ${tech.unsupportedNote}`),
      ),
      '',
      'An empty section below does not mean the repository has nothing there.',
    ]);
  }

  interface Row {
    readonly id: ExtractorId;
    readonly title: string;
    readonly page: string;
    readonly count: string;
    readonly gaps: string;
  }

  const rows: Row[] = EXTRACTOR_IDS.map((id) => {
    const result = run.results.get(id);
    const file = PAGE_FILES[id];
    const linked = file === undefined ? PAGE_TITLES[id] : `[${PAGE_TITLES[id]}](${file})`;

    if (result === undefined) {
      return { id, title: PAGE_TITLES[id], page: linked, count: '_not run_', gaps: '—' };
    }
    if (!result.applicable) {
      return { id, title: PAGE_TITLES[id], page: linked, count: '_not applicable_', gaps: '—' };
    }
    return {
      id,
      title: PAGE_TITLES[id],
      page: linked,
      count: String(result.entries.length),
      gaps: result.gaps.length === 0 ? '—' : String(result.gaps.length),
    };
  });

  body += section(
    'Contents',
    table(
      [
        { header: 'Section', render: (row: Row) => row.page },
        { header: 'Entries', render: (row: Row) => row.count },
        { header: 'Not determined', render: (row: Row) => row.gaps },
      ],
      rows,
    ),
  );

  body += section(
    'Diagrams',
    [
      '| Diagram | Shows |',
      '| --- | --- |',
      '| [Sitemap](diagrams/sitemap.mmd) | The route tree |',
      '| [ERD](diagrams/erd.mmd) | Tables and their relations |',
      '| [Modules](diagrams/modules.mmd) | Internal dependency graph |',
      '| [Integrations](diagrams/integrations.mmd) | External services this system talks to |',
      '',
    ].join('\n'),
  );

  const technologies = run.stack.technologies;
  if (technologies.length > 0) {
    body += section(
      'Detected stack',
      table(
        [
          { header: 'Technology', render: (tech: (typeof technologies)[number]) => tech.name },
          { header: 'Category', render: (tech: (typeof technologies)[number]) => cell(tech.category) },
          {
            header: 'Where',
            render: (tech: (typeof technologies)[number]) =>
              tech.workspace === '' ? '_repo root_' : `\`${tech.workspace}/\``,
          },
          {
            header: 'Documented',
            render: (tech: (typeof technologies)[number]) =>
              tech.covers.length > 0
                ? tech.covers.join(', ')
                : tech.category === 'language' || tech.category === 'datastore'
                  ? '_n/a_'
                  : '**no**',
          },
        ],
        technologies,
      ),
    );
  }

  if (findings !== undefined) {
    body += renderFindingsSection(findings, run.config.outDir);
  }

  body += section(
    'How to read this',
    [
      '- Every row links to `file:line` in the source. If a statement looks wrong, the code is one click away.',
      '- **Not determined** lists what static analysis could not establish. It is not a list of defects,',
      '  and an empty value in a table never means "none" unless the page says so.',
      '- Entries marked `~heuristic` were read by pattern matching rather than a real parser, and should',
      '  be verified before being relied on.',
      '- This directory is regenerated by `docgen extract`. Hand edits are lost.',
      '',
    ].join('\n'),
  );

  return body;
}

/**
 * Cross-extractor findings (SPEC 6.4).
 *
 * Rendered as observations with their evidence. Each says what it compared and
 * what it cannot prove, because a list of "dead code" that turns out to be
 * loaded dynamically destroys trust in every other line on the page.
 */
function renderFindingsSection(report: FindingsReport, outDir: string): string {
  let body = '';

  for (const finding of report.findings) {
    if (finding.unavailable !== undefined) {
      body += section(finding.title, `_Not run: ${finding.unavailable}_
`, 3);
      continue;
    }
    if (finding.items.length === 0) {
      body += section(finding.title, `${finding.description}

_None found._
`, 3);
      continue;
    }

    const rows = sortItems(finding.items);
    body += section(
      `${finding.title} (${rows.length})`,
      `${finding.description}

${table(
        [
          { header: 'Item', render: (item: (typeof rows)[number]) => `\`${item.label}\`` },
          { header: 'Detail', render: (item: (typeof rows)[number]) => cell(item.detail) },
          {
            header: 'Source',
            render: (item: (typeof rows)[number]) =>
              item.source === undefined || item.source.file === item.label
                ? '—'
                : sourceLink(item.source, outDir),
          },
        ],
        rows,
      )}`,
      3,
    );
  }

  return section(
    `Findings (${report.totalItems})`,
    `These compare one extractor's output against another's. They are observations for a human to
judge, not defects.

${body}`,
  );
}
