import { createHash } from 'node:crypto';
import type { Gap, Skip } from '../../types/core.js';
import type { SchemaEntry, SchemaResult } from '../../types/entries.js';
import type { Extractor, ExtractorContext } from '../types.js';
import { inapplicable, skip } from '../types.js';
import { prismaProvider } from './prisma.js';
import { mongooseProvider } from './mongoose.js';
import { sqlDdlProvider } from './sql-ddl.js';
import { typeormProvider, sequelizeProvider } from './decorated-orm.js';
import { pythonModelsProvider } from './python-models.js';
import type { SchemaProvider } from './types.js';

/**
 * Every table and collection the repo defines.
 *
 * Providers run independently and additively, because a repo genuinely can hold
 * a Prisma service, a Mongoose service, and raw SQL migrations at once. None of
 * them is authoritative over the others, so all results are kept and any
 * collision between them is reported rather than silently resolved.
 */
const PROVIDERS: readonly SchemaProvider[] = Object.freeze([
  prismaProvider,
  mongooseProvider,
  sqlDdlProvider,
  typeormProvider,
  sequelizeProvider,
  pythonModelsProvider,
]);

export const schemaExtractor: Extractor<SchemaEntry> = {
  id: 'schema',
  title: 'Database schema',

  async run(context: ExtractorContext): Promise<SchemaResult> {
    const startedAt = Date.now();

    const entries: SchemaEntry[] = [];
    const gaps: Gap[] = [];
    const skips: Skip[] = [];
    const detected: string[] = [];

    // Migrations generated by an ORM are derived output, not an independent
    // declaration. Reading both the ORM schema and the SQL it generates
    // double-counts every table and reports the two as having drifted apart,
    // which is a fabricated finding.
    const derivedMigrationGlobs: string[] = [];

    for (const provider of PROVIDERS) {
      const result = await provider.run({
        root: context.root,
        exclude:
          provider.id === 'sql-ddl'
            ? [...context.config.effectiveExclude, ...derivedMigrationGlobs]
            : context.config.effectiveExclude,
      });

      if (provider.id === 'prisma' && result.entries.length > 0) {
        derivedMigrationGlobs.push('**/prisma/migrations/**');
      }

      if (result.entries.length === 0 && result.gaps.length === 0) continue;

      detected.push(provider.id);
      entries.push(...result.entries);
      gaps.push(...result.gaps);
      context.logger.debug(`schema: ${provider.id} found ${result.entries.length} entries`);
    }

    if (detected.length === 0) {
      return inapplicable<SchemaEntry>(
        'schema',
        [
          skip(
            'schema',
            'no-schema-source-detected',
            'No Prisma schema, Mongoose model, SQL migration, TypeORM entity, Sequelize model, ' +
              'or Python model was found.',
          ),
        ],
        Date.now() - startedAt,
      );
    }

    const { deduped, duplicateGaps } = resolveDuplicates(entries);

    return {
      extractor: 'schema',
      applicable: true,
      detected: [...detected].sort(),
      entries: [...deduped].sort((a, b) => a.name.localeCompare(b.name) || a.id.localeCompare(b.id)),
      gaps: [...gaps, ...duplicateGaps].sort(
        (a, b) =>
          a.kind.localeCompare(b.kind) ||
          (a.source?.file ?? '').localeCompare(b.source?.file ?? '') ||
          a.message.localeCompare(b.message),
      ),
      skips,
      durationMs: Date.now() - startedAt,
    };
  },
};

/**
 * Two providers naming the same table is worth reporting, not silently merging.
 *
 * It usually means a migration and an ORM model have drifted apart, and which
 * one the database actually matches is a question only a human can answer — so
 * both are kept and the disagreement is surfaced.
 */
function resolveDuplicates(entries: readonly SchemaEntry[]): {
  deduped: readonly SchemaEntry[];
  duplicateGaps: readonly Gap[];
} {
  const byId = new Map<string, SchemaEntry[]>();
  for (const entry of entries) {
    const bucket = byId.get(entry.id);
    if (bucket === undefined) byId.set(entry.id, [entry]);
    else bucket.push(entry);
  }

  const deduped: SchemaEntry[] = [];
  const duplicateGaps: Gap[] = [];

  for (const [, bucket] of byId) {
    if (bucket.length === 1) {
      deduped.push(bucket[0] as SchemaEntry);
      continue;
    }

    const first = bucket[0] as SchemaEntry;
    const files = bucket.map((entry) => entry.source.file).sort();
    duplicateGaps.push({
      extractor: 'schema',
      kind: 'duplicate-table-definition',
      message:
        `Table '${first.name}' is defined in ${bucket.length} places: ${files.join(', ')}. ` +
        'These may have drifted apart; docgen does not choose between them.',
      source: { file: files[0] as string },
    });

    for (const entry of bucket) {
      const suffix = createHash('sha256').update(entry.source.file).digest('hex').slice(0, 8);
      deduped.push({ ...entry, id: `${entry.id}#${suffix}` });
    }
  }

  return { deduped, duplicateGaps };
}
