import fs from 'node:fs/promises';
import path from 'node:path';
import { GENERATED_MARKER } from '../render/markdown.js';
import { DocgenError } from './errors.js';

/** Output may share a docs directory, but cannot own the repository or its stores. */
export function isSafeOutputDirectory(value: string): boolean {
  const relative = value.replace(/\\/g, '/');
  const normalized = path.posix.normalize(relative).replace(/\/+$/, '');
  return relative.trim() === relative && relative.length > 0 &&
    !/[\u0000-\u001f\u007f]/.test(relative) &&
    !path.posix.isAbsolute(relative) && !path.win32.isAbsolute(value) &&
    !/^[a-zA-Z]:/.test(relative) && normalized !== '.' && normalized !== '' &&
    !relative.split('/').includes('..') &&
    !relative.split('/').some((segment) => segment !== '.' && /[. ]$/.test(segment)) &&
    !/(?:^|\/)(?:\.git|node_modules|\.docgen|\.cards|\.answers|\.requirements|\.features|\.plans|\.changes|\.legacy|\.governance|\.migrations|\.security)(?:\/|$)/i.test(relative);
}

export function normalizeOutputDirectory(value: string): string {
  if (!isSafeOutputDirectory(value)) {
    throw new DocgenError({
      code: 'output-directory-invalid',
      message: `Generated output must use a repository-relative directory outside protected stores: '${value}'.`,
      remedy: 'Use a directory such as docs/generated. The repository root, parent paths, and governed stores are not valid output destinations.',
    });
  }
  return path.posix.normalize(value.replace(/\\/g, '/')).replace(/\/+$/, '');
}

/** Reject traversal and symlink components before reading or changing generated output. */
export async function assertGeneratedPath(root: string, relative: string): Promise<void> {
  const resolvedRoot = path.resolve(root);
  const target = path.resolve(resolvedRoot, relative);
  const relation = path.relative(resolvedRoot, target);
  if (relation === '' || relation === '..' || relation.startsWith(`..${path.sep}`) || path.isAbsolute(relation)) {
    throw new DocgenError({ code: 'generated-path-outside-root', message: `Generated path is outside the target repository: ${relative}.`, remedy: 'Use a path inside the target repository.', file: relative });
  }
  let current = resolvedRoot;
  for (const segment of relation.split(path.sep)) {
    current = path.join(current, segment);
    try {
      if ((await fs.lstat(current)).isSymbolicLink()) {
        throw new DocgenError({ code: 'generated-path-symlink', message: `Generated output may not traverse a symbolic link: ${relative}.`, remedy: 'Choose an ordinary directory inside the target repository.', file: relative });
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return;
      throw error;
    }
  }
}

export function isGeneratedFile(file: string, contents: string): boolean {
  if (file.endsWith('.mmd')) return contents.startsWith('%% Generated by docgen. Do not edit by hand.');
  if (!file.endsWith('.md')) return false;
  let header = contents.replace(/\r\n/g, '\n').trimStart();
  if (header.startsWith('---\n')) {
    const end = header.indexOf('\n---\n', 4);
    if (end < 0 || !/^generated: true$/m.test(header.slice(4, end))) return false;
    header = header.slice(end + 5).trimStart();
  }
  // Quoted examples elsewhere in a human document do not confer ownership.
  return header === GENERATED_MARKER || header.startsWith(`${GENERATED_MARKER}\n`);
}

/** Preflight the entire batch so a collision does not leave a half-written baseline. */
export async function assertGeneratedTargets(root: string, files: readonly string[]): Promise<void> {
  for (const file of files) {
    await assertGeneratedPath(root, file);
    let existing: string;
    try { existing = await fs.readFile(path.join(root, file), 'utf8'); }
    catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') continue;
      throw error;
    }
    if (!isGeneratedFile(file, existing)) {
      throw new DocgenError({ code: 'generated-file-owned', message: `Refusing to overwrite an unmarked file: ${file}.`, remedy: 'Choose a different output directory or explicitly relocate the human-owned document before regenerating.', file });
    }
  }
}
