import type { ConfigResult, DepsResult, ModuleEntry, RoutesResult, SchemaResult } from '../types/entries.js';
import { safeNodeId } from './mermaid-validate.js';

/**
 * Mermaid diagrams, emitted as `.mmd` text so they diff in pull requests and
 * render natively in GitHub and Notion (SPEC 6.2).
 *
 * Every diagram is bounded. A graph past its node budget is aggregated rather
 * than emitted whole: a 400-node hairball is not a diagram, it is a picture of
 * one, and it tells a reader less than the table it came from.
 */

/** Mermaid node ids must be identifier-safe, reserved-word-safe, and stable. */
const nodeId = safeNodeId;

/**
 * Quote and escape a Mermaid label.
 *
 * Square brackets are the real hazard: `id["[slug]"]` closes the node shape at
 * the first `]` and breaks the diagram, and Next.js dynamic segments put
 * brackets in almost every route label. Mermaid's own `#nn;` escapes are used
 * rather than HTML entities, because those work whether or not the renderer has
 * HTML labels enabled — GitHub and Notion do not configure it the same way.
 */
function label(value: string): string {
  const escaped = value
    .replace(/#/g, '#35;')
    .replace(/"/g, '#quot;')
    .replace(/\[/g, '#91;')
    .replace(/\]/g, '#93;')
    .replace(/\(/g, '#40;')
    .replace(/\)/g, '#41;')
    .replace(/\{/g, '#123;')
    .replace(/\}/g, '#125;');
  return `"${escaped}"`;
}

const HEADER = '%% Generated by docgen. Do not edit by hand.';

// ── sitemap ──────────────────────────────────────────────────────────────────

/** The route tree, as a QA engineer would navigate it. */
export function renderSitemap(routes: RoutesResult | undefined, maxNodes: number): string {
  const screens = (routes?.entries ?? []).filter(
    (entry) => entry.kind === 'page' || entry.kind === 'redirect',
  );

  if (screens.length === 0) {
    return `${HEADER}\ngraph TD\n  empty[${label('No routes were extracted')}]\n`;
  }

  const lines = [HEADER, 'graph TD'];
  const emitted = new Set<string>();
  // Edges repeat whenever screens share an ancestor path, so they are
  // deduplicated among themselves. Node declarations are not: deduplicating
  // whole lines is how structural syntax gets silently dropped.
  const edges = new Set<string>();
  const truncated = screens.length > maxNodes;
  const shown = truncated ? screens.slice(0, maxNodes) : screens;

  lines.push(`  root[${label('/')}]`);
  emitted.add('/');

  for (const screen of shown) {
    const segments = screen.path.split('/').filter((part) => part.length > 0);
    let parentPath = '/';

    for (let depth = 0; depth < segments.length; depth += 1) {
      const currentPath = `/${segments.slice(0, depth + 1).join('/')}`;
      if (!emitted.has(currentPath)) {
        emitted.add(currentPath);
        lines.push(`  ${nodeId('r', currentPath)}[${label(segments[depth] as string)}]`);
      }
      edges.add(
        `  ${parentPath === '/' ? 'root' : nodeId('r', parentPath)} --> ${nodeId('r', currentPath)}`,
      );
      parentPath = currentPath;
    }
  }

  if (truncated) {
    lines.push(`  more[${label(`… ${screens.length - maxNodes} more screens — see routes.md`)}]`);
    edges.add('  root --> more');
  }

  lines.push(...[...edges].sort());
  return `${lines.join('\n')}\n`;
}

// ── ERD ──────────────────────────────────────────────────────────────────────

/** Mermaid erDiagram from the extracted schema. */
export function renderErd(schema: SchemaResult | undefined, maxNodes: number): string {
  const tables = schema?.entries ?? [];
  if (tables.length === 0) {
    return `${HEADER}\nerDiagram\n  NO_SCHEMA_EXTRACTED {\n    string note\n  }\n`;
  }

  const shown = tables.slice(0, maxNodes);
  const names = new Set(shown.map((table) => table.name));
  // Structural lines are never deduplicated: `}` closes every block and
  // collapsing repeats would leave all but the first table unterminated.
  const lines = [HEADER, 'erDiagram'];
  const relationLines = new Set<string>();

  for (const table of shown) {
    lines.push(`  ${nodeId('t', table.name)} {`);
    // Field count is bounded too: a 60-column table renders as an unreadable box.
    for (const field of table.fields.slice(0, 20)) {
      const type = field.type.replace(/[^A-Za-z0-9_]/g, '_') || 'unknown';
      const key = field.isPrimaryKey === true ? ' PK' : field.isUnique === true ? ' UK' : '';
      lines.push(`    ${type} ${field.name.replace(/[^A-Za-z0-9_]/g, '_')}${key}`);
    }
    // The attribute name must not start with a digit: Mermaid's ER grammar
    // expects an ATTRIBUTE_WORD there and rejects the whole diagram otherwise,
    // so a wide table would silently render as a parse error on GitHub.
    if (table.fields.length > 20) {
      lines.push(`    more fields_not_shown_${table.fields.length - 20}`);
    }
    lines.push('  }');
  }

  for (const table of shown) {
    for (const relation of table.relations) {
      // Only draw an edge when both ends are on the diagram.
      const target = shown.find(
        (candidate) => candidate.name === relation.targetModel || candidate.modelName === relation.targetModel,
      );
      if (target === undefined || !names.has(table.name)) continue;

      const cardinality =
        relation.cardinality === 'one-to-one'
          ? '||--||'
          : relation.cardinality === 'many-to-many'
            ? '}o--o{'
            : relation.cardinality === 'one-to-many'
              ? '||--o{'
              : '}o--||';
      relationLines.add(
        `  ${nodeId('t', table.name)} ${cardinality} ${nodeId('t', target.name)} : ${label(relation.field)}`,
      );
    }
  }

  // Only relations are deduplicated, and only among themselves.
  lines.push(...[...relationLines].sort());

  if (tables.length > maxNodes) {
    lines.push(`  %% ${tables.length - maxNodes} further tables omitted — see schema.md`);
  }
  return `${lines.join('\n')}\n`;
}

// ── module graph ─────────────────────────────────────────────────────────────

/**
 * The internal dependency graph, collapsed to directories when it exceeds the
 * node budget (SPEC 6.3). The note about collapsing is emitted into the diagram
 * so a reader is never shown an aggregate believing it is the detail.
 */
export function renderModules(deps: DepsResult | undefined, maxNodes: number): string {
  const modules = deps?.entries ?? [];
  if (modules.length === 0) {
    return `${HEADER}\ngraph LR\n  empty[${label('No modules were extracted')}]\n`;
  }

  const collapsed = modules.length > maxNodes;
  const lines = [HEADER, 'graph LR'];
  if (collapsed) {
    lines.push(
      `  %% ${modules.length} modules exceeded the ${maxNodes}-node budget;`,
      '  %% collapsed to top-level directories. See modules in deps output for detail.',
    );
  }

  const keyOf = (modulePath: string): string =>
    collapsed ? (modulePath.split('/').slice(0, 2).join('/') || modulePath) : modulePath;

  const nodes = new Set<string>();
  const edges = new Set<string>();

  for (const entry of modules) {
    const from = keyOf(entry.module);
    nodes.add(from);
    for (const imported of entry.imports) {
      const to = keyOf(imported);
      if (to === from) continue;
      nodes.add(to);
      edges.add(`  ${nodeId('m', from)} --> ${nodeId('m', to)}`);
    }
  }

  for (const node of [...nodes].sort()) lines.push(`  ${nodeId('m', node)}[${label(node)}]`);
  lines.push(...[...edges].sort());

  // A cycle is the one thing in this graph worth highlighting on sight.
  const cycles = deps?.cycles ?? [];
  if (cycles.length > 0) {
    lines.push(`  %% ${cycles.length} import cycle(s) detected:`);
    for (const cycle of cycles.slice(0, 10)) {
      lines.push(`  %%   ${[...cycle, cycle[0]].join(' -> ')}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

// ── integrations ─────────────────────────────────────────────────────────────

/** External package names that identify a third-party service. */
const SERVICE_BY_PACKAGE: Readonly<Record<string, string>> = Object.freeze({
  stripe: 'Stripe',
  '@stripe/stripe-js': 'Stripe',
  twilio: 'Twilio',
  '@sendgrid/mail': 'SendGrid',
  nodemailer: 'SMTP mail',
  '@aws-sdk/client-s3': 'AWS S3',
  '@aws-sdk/client-ses': 'AWS SES',
  'aws-sdk': 'AWS',
  firebase: 'Firebase',
  'firebase-admin': 'Firebase',
  '@supabase/supabase-js': 'Supabase',
  '@sentry/node': 'Sentry',
  '@sentry/nextjs': 'Sentry',
  algoliasearch: 'Algolia',
  '@elastic/elasticsearch': 'Elasticsearch',
  openai: 'OpenAI',
  '@anthropic-ai/sdk': 'Anthropic',
  '@langchain/mongodb': 'LangChain',
  razorpay: 'Razorpay',
  amqplib: 'RabbitMQ',
  ioredis: 'Redis',
  redis: 'Redis',
  mongoose: 'MongoDB',
  pg: 'PostgreSQL',
  '@prisma/client': 'PostgreSQL (Prisma)',
  axios: 'HTTP (axios)',
  'node-fetch': 'HTTP (fetch)',
});

/** Env var prefixes that name a service even when no SDK is imported. */
const SERVICE_BY_ENV_PREFIX: readonly (readonly [RegExp, string])[] = Object.freeze([
  [/^STRIPE_/, 'Stripe'],
  [/^TWILIO_/, 'Twilio'],
  [/^SENDGRID_/, 'SendGrid'],
  [/^AWS_/, 'AWS'],
  [/^FIREBASE_/, 'Firebase'],
  [/^SUPABASE_/, 'Supabase'],
  [/^SENTRY_/, 'Sentry'],
  [/^RAZORPAY_/, 'Razorpay'],
  [/^SMTP_/, 'SMTP mail'],
  [/^GOOGLE_MAPS?_/, 'Google Maps'],
  [/^ZOHO_/, 'Zoho'],
  [/^OPENAI_/, 'OpenAI'],
  [/^ANTHROPIC_/, 'Anthropic'],
]);

/**
 * External services this system talks to.
 *
 * Derived from two independent signals — an imported SDK, and an environment
 * variable named after a provider. Each edge records which signal produced it,
 * so a reader can tell a proven dependency from a strong hint.
 */
export function renderIntegrations(args: {
  deps: DepsResult | undefined;
  config: ConfigResult | undefined;
  projectName: string;
}): string {
  const services = new Map<string, Set<string>>();

  const add = (service: string, evidence: string): void => {
    const bucket = services.get(service) ?? new Set<string>();
    bucket.add(evidence);
    services.set(service, bucket);
  };

  const externals = new Set<string>();
  for (const entry of args.deps?.entries ?? []) {
    for (const external of entry.externals) externals.add(external);
  }
  for (const packageName of [...externals].sort()) {
    const service = SERVICE_BY_PACKAGE[packageName];
    if (service !== undefined) add(service, `imports ${packageName}`);
  }

  for (const entry of args.config?.entries ?? []) {
    for (const [pattern, service] of SERVICE_BY_ENV_PREFIX) {
      if (pattern.test(entry.name)) add(service, `env ${entry.name}`);
    }
  }

  if (services.size === 0) {
    return `${HEADER}\ngraph LR\n  empty[${label('No external services were identified')}]\n`;
  }

  const app = nodeId('svc', args.projectName);
  const lines = [HEADER, 'graph LR', `  ${app}[${label(args.projectName)}]`];

  for (const service of [...services.keys()].sort()) {
    const evidence = [...(services.get(service) ?? [])].sort();
    lines.push(`  ${nodeId('ext', service)}[${label(service)}]`);
    lines.push(`  ${app} --> |${label(evidence[0] as string)}| ${nodeId('ext', service)}`);
  }

  return `${lines.join('\n')}\n`;
}

/** Modules and their imports, for callers that need the raw shape. */
export type { ModuleEntry };
