import { execFile } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import { promisify } from 'node:util';
import { DocgenError } from '../util/errors.js';
import type { AdapterOutcome } from './install.js';

const execFileAsync = promisify(execFile);
export const PRE_PUSH_HOOK_PATH = '.githooks/pre-push';
const MARKER = '# Generated by docgen. Run `docgen init --hooks` to update.';

export function renderPrePushHook(invocation: string): string {
  return `#!/bin/sh
${MARKER}
set -eu
zero=0000000000000000000000000000000000000000
empty_tree=4b825dc642cb6eb9a060e54bf8d69288fbee4904
remote=\${1:-origin}
received_ref=0
while read -r local_ref local_sha remote_ref remote_sha; do
  received_ref=1
  # Deleting a remote ref introduces no code to govern.
  [ "$local_sha" = "$zero" ] && continue
  pushed_commit=$(git rev-parse --verify "$local_sha^{commit}")
  if [ "$pushed_commit" != "$(git rev-parse HEAD)" ]; then
    echo "docgen: check out the pushed commit before running its documentation gate." >&2
    exit 1
  fi
  if [ "$remote_sha" != "$zero" ]; then
    if ! git cat-file -e "$remote_sha^{commit}" 2>/dev/null; then
      echo "docgen: fetch the remote comparison commit before pushing." >&2
      exit 1
    fi
    base=$remote_sha
  else
    default_ref=$(git symbolic-ref --quiet "refs/remotes/$remote/HEAD" 2>/dev/null || true)
    base=$empty_tree
    if [ -n "$default_ref" ]; then
      base=$(git merge-base "$local_sha" "$default_ref" || printf '%s' "$empty_tree")
    fi
  fi
  ${invocation} check --base "$base"
done
# Also support a manual invocation without Git's ref list on stdin.
if [ "$received_ref" = 0 ]; then
  base=HEAD
  ${invocation} check --base "$base"
fi
`;
}

export async function installGitHook(root: string, invocation: string): Promise<AdapterOutcome> {
  try { await execFileAsync('git', ['rev-parse', '--git-dir'], { cwd: root, timeout: 5_000, windowsHide: true }); }
  catch { throw new DocgenError({ code: 'git-hooks-not-repository', message: 'Git hooks require a Git repository.', remedy: 'Run `git init` first, or omit `--hooks`.' }); }
  let configured = '';
  try {
    const result = await execFileAsync('git', ['config', '--local', '--get', 'core.hooksPath'], { cwd: root, timeout: 5_000, windowsHide: true });
    configured = result.stdout.trim();
  } catch { /* no custom path */ }
  if (configured.length > 0 && configured !== '.githooks') {
    throw new DocgenError({
      code: 'git-hooks-path-owned',
      message: `Git already uses core.hooksPath '${configured}'.`,
      remedy: `Chain '${PRE_PUSH_HOOK_PATH}' from the existing hook system, or remove that setting before retrying.`,
    });
  }
  const file = path.join(root, PRE_PUSH_HOOK_PATH);
  let existing = '';
  try { existing = await fs.readFile(file, 'utf8'); } catch { /* absent */ }
  if (existing.length > 0 && !existing.includes(MARKER)) {
    throw new DocgenError({
      code: 'git-hook-owned',
      message: `${PRE_PUSH_HOOK_PATH} already contains a team-owned hook.`,
      remedy: 'Chain `docgen check` from that hook manually. Docgen did not overwrite it.',
      file,
    });
  }
  const contents = renderPrePushHook(invocation);
  const action = existing.replace(/\r\n/g, '\n') === contents ? 'unchanged' : existing.length === 0 ? 'created' : 'updated';
  if (action !== 'unchanged') {
    await fs.mkdir(path.dirname(file), { recursive: true });
    await fs.writeFile(file, contents, { encoding: 'utf8', mode: 0o755 });
    await fs.chmod(file, 0o755);
  }
  if (configured !== '.githooks') {
    await execFileAsync('git', ['config', '--local', 'core.hooksPath', '.githooks'], { cwd: root, timeout: 5_000, windowsHide: true });
  }
  return { id: 'hooks', file: PRE_PUSH_HOOK_PATH, action };
}
