import { execFile } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import { promisify } from 'node:util';
import { DocgenError } from '../util/errors.js';
import type { AdapterOutcome } from './install.js';

const execFileAsync = promisify(execFile);
export const PRE_PUSH_HOOK_PATH = '.githooks/pre-push';
const MARKER = '# Generated by docgen. Run `docgen init --hooks` to update.';

export function renderPrePushHook(invocation: string): string {
  return `#!/bin/sh\n${MARKER}\nset -eu\n${invocation} check\n`;
}

export async function installGitHook(root: string, invocation: string): Promise<AdapterOutcome> {
  try { await execFileAsync('git', ['rev-parse', '--git-dir'], { cwd: root, timeout: 5_000, windowsHide: true }); }
  catch { throw new DocgenError({ code: 'git-hooks-not-repository', message: 'Git hooks require a Git repository.', remedy: 'Run `git init` first, or omit `--hooks`.' }); }
  let configured = '';
  try {
    const result = await execFileAsync('git', ['config', '--local', '--get', 'core.hooksPath'], { cwd: root, timeout: 5_000, windowsHide: true });
    configured = result.stdout.trim();
  } catch { /* no custom path */ }
  if (configured.length > 0 && configured !== '.githooks') {
    throw new DocgenError({
      code: 'git-hooks-path-owned',
      message: `Git already uses core.hooksPath '${configured}'.`,
      remedy: `Chain '${PRE_PUSH_HOOK_PATH}' from the existing hook system, or remove that setting before retrying.`,
    });
  }
  const file = path.join(root, PRE_PUSH_HOOK_PATH);
  let existing = '';
  try { existing = await fs.readFile(file, 'utf8'); } catch { /* absent */ }
  if (existing.length > 0 && !existing.includes(MARKER)) {
    throw new DocgenError({
      code: 'git-hook-owned',
      message: `${PRE_PUSH_HOOK_PATH} already contains a team-owned hook.`,
      remedy: 'Chain `docgen check` from that hook manually. Docgen did not overwrite it.',
      file,
    });
  }
  const contents = renderPrePushHook(invocation);
  const action = existing.replace(/\r\n/g, '\n') === contents ? 'unchanged' : existing.length === 0 ? 'created' : 'updated';
  if (action !== 'unchanged') {
    await fs.mkdir(path.dirname(file), { recursive: true });
    await fs.writeFile(file, contents, { encoding: 'utf8', mode: 0o755 });
    await fs.chmod(file, 0o755);
  }
  if (configured !== '.githooks') {
    await execFileAsync('git', ['config', '--local', 'core.hooksPath', '.githooks'], { cwd: root, timeout: 5_000, windowsHide: true });
  }
  return { id: 'hooks', file: PRE_PUSH_HOOK_PATH, action };
}
