import fg from 'fast-glob';
import fs from 'node:fs/promises';
import path from 'node:path';
import YAML from 'yaml';
import { DocgenError, describeUnknownError } from '../util/errors.js';
import { ANSWERS_DIR } from '../config/paths.js';
import { toPosix } from '../util/paths.js';
import { compareStrings } from '../util/sort.js';

/**
 * Developer answers, on record.
 *
 * This is the most important file docgen writes. An answer here is the only
 * thing that promotes a claim from `inferred` to `verified`, and it must
 * survive refactors, regenerations, and prompt changes — so it is stored as
 * plain YAML in the repository, keyed by surface and question, readable and
 * editable by hand, and never regenerated by the tool.
 */

export interface Answer {
  /** Matches the `id` of the unknown it answers. */
  readonly questionId: string;
  readonly question: string;
  /** What the developer said. */
  readonly answer: string;
  /** Who answered — git identity, so a reader can follow up. */
  readonly answeredBy: string;
  /** ISO-8601. */
  readonly answeredAt: string;
  /** Free-text elaboration, when the developer added one. */
  readonly note?: string;
}

export interface SurfaceAnswers {
  readonly surfaceId: string;
  readonly slug: string;
  readonly answers: readonly Answer[];
}

/** Answers live beside the docs but are authored by humans, not generated. */
export { ANSWERS_DIR } from '../config/paths.js';

function answerFile(root: string, slug: string): string {
  return path.join(root, ANSWERS_DIR, `${slug}.yaml`);
}

/**
 * Load every recorded answer, keyed by surface id.
 *
 * A corrupt answer file is a loud error. These are ground truth: silently
 * ignoring one would demote confirmed knowledge back to a guess without anyone
 * noticing.
 */
export async function loadAnswers(root: string): Promise<ReadonlyMap<string, SurfaceAnswers>> {
  const files = (
    await fg([`${ANSWERS_DIR}/*.yaml`, `${ANSWERS_DIR}/*.yml`], { cwd: root, onlyFiles: true })
  )
    .map(toPosix)
    .sort(compareStrings);

  const bySurface = new Map<string, SurfaceAnswers>();

  for (const relative of files) {
    const absolute = path.join(root, relative);
    let parsed: unknown;
    try {
      parsed = YAML.parse(await fs.readFile(absolute, 'utf8'));
    } catch (cause) {
      throw new DocgenError({
        code: 'answers-unparseable',
        message: `${relative} is not valid YAML: ${describeUnknownError(cause)}`,
        remedy:
          'Fix the YAML syntax. These files are recorded developer answers and are treated as ' +
          'ground truth, so docgen will not skip one it cannot read.',
        file: relative,
        cause,
      });
    }

    if (parsed === null || typeof parsed !== 'object') continue;
    const record = parsed as Record<string, unknown>;
    const surfaceId = typeof record['surfaceId'] === 'string' ? record['surfaceId'] : undefined;
    const slug = typeof record['slug'] === 'string' ? record['slug'] : path.posix.basename(relative, path.posix.extname(relative));
    if (surfaceId === undefined) continue;

    const rawAnswers = Array.isArray(record['answers']) ? record['answers'] : [];
    const answers: Answer[] = [];
    for (const entry of rawAnswers) {
      if (entry === null || typeof entry !== 'object') continue;
      const value = entry as Record<string, unknown>;
      const questionId = value['questionId'];
      const answer = value['answer'];
      if (typeof questionId !== 'string' || typeof answer !== 'string') continue;

      answers.push({
        questionId,
        question: typeof value['question'] === 'string' ? value['question'] : '',
        answer,
        answeredBy: typeof value['answeredBy'] === 'string' ? value['answeredBy'] : 'unknown',
        answeredAt: typeof value['answeredAt'] === 'string' ? value['answeredAt'] : '',
        ...(typeof value['note'] === 'string' ? { note: value['note'] } : {}),
      });
    }

    bySurface.set(surfaceId, { surfaceId, slug, answers });
  }

  return bySurface;
}

/**
 * Record an answer, merging into whatever is already on file.
 *
 * Re-answering a question replaces the previous answer rather than appending:
 * two conflicting answers to one question would leave a reader with no way to
 * tell which is current.
 */
export async function recordAnswer(args: {
  root: string;
  surfaceId: string;
  slug: string;
  answer: Answer;
}): Promise<void> {
  const existing = (await loadAnswers(args.root)).get(args.surfaceId);
  const kept = (existing?.answers ?? []).filter(
    (candidate) => candidate.questionId !== args.answer.questionId,
  );

  const merged: SurfaceAnswers = {
    surfaceId: args.surfaceId,
    slug: args.slug,
    answers: [...kept, args.answer].sort((a, b) => compareStrings(a.questionId, b.questionId)),
  };

  const file = answerFile(args.root, args.slug);
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, renderAnswersFile(merged), 'utf8');
}

/** YAML with a header explaining what the file is for, since humans edit it. */
export function renderAnswersFile(surface: SurfaceAnswers): string {
  const header = [
    '# Developer answers recorded by docgen.',
    '#',
    '# These are ground truth. Every answer here promotes a section of the',
    '# generated documentation from "inferred by a model" to "verified".',
    '# Edit by hand if an answer was wrong — docgen never overwrites this file',
    '# except to add or replace an answer you gave it.',
    '',
  ].join('\n');

  return `${header}${YAML.stringify(
    {
      surfaceId: surface.surfaceId,
      slug: surface.slug,
      answers: surface.answers.map((answer) => ({
        questionId: answer.questionId,
        question: answer.question,
        answer: answer.answer,
        answeredBy: answer.answeredBy,
        answeredAt: answer.answeredAt,
        ...(answer.note === undefined ? {} : { note: answer.note }),
      })),
    },
    { lineWidth: 100 },
  )}`;
}

/** The answers for one surface, rendered for injection into a prompt. */
export function renderAnswersForPrompt(answers: readonly Answer[]): string {
  if (answers.length === 0) return '_None yet._';
  return answers
    .map((answer) => `- **${answer.question || answer.questionId}** → ${answer.answer} _(${answer.answeredBy})_`)
    .join('\n');
}
